language: generic
sudo: required
services:
  - docker

env:
  COMPOSE_VERSION: 1.18.0
  RABBITMQ_DEFAULT_USER: nuntium.test
  RABBITMQ_DEFAULT_PASS: nuntium.test
  RABBITMQ_DEFAULT_VHOST: /nuntium/test

before_install:
 - curl -L https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
 - chmod +x docker-compose
 - sudo mv docker-compose /usr/local/bin

install:
  - docker-compose pull

before_script:
  - docker-compose build
  - docker-compose run --rm web bundle install --without development debug webserver
  - docker-compose run --rm web rake db:setup
  - docker-compose run --rm web rake db:test:prepare

script:
  - docker-compose run --rm web rake test

notifications:
  slack:
    secure: aQ0ckzIpsYWvv7yaGPZ0kqFdE/3ljOW/2+PAr2jyxDIx8vtQA/tC3CnyQ66phpS0/AZTQjez/bbL6ZA7r1NZOYg96S5cV9jxwkMml+jzrYAD0nl/cTRZzz4MLIjQu53vuFEt/Cr08YWrB9xRqd0mA8kMpwPwp7nxODzJXOiakvk=

deploy:
  skip_cleanup: true
  provider: script
  script: "./travis-build.sh"
  on:
    all_branches: true
