sudo: false
language: ruby
rvm:
- 1.9.3
bundler_args: "--without development debug webserver"
services:
- rabbitmq
- memcached
before_install: gem update bundler
before_script:
- bundle exec rake db:setup
script:
- bundle exec rake test
notifications:
  slack:
    secure: aQ0ckzIpsYWvv7yaGPZ0kqFdE/3ljOW/2+PAr2jyxDIx8vtQA/tC3CnyQ66phpS0/AZTQjez/bbL6ZA7r1NZOYg96S5cV9jxwkMml+jzrYAD0nl/cTRZzz4MLIjQu53vuFEt/Cr08YWrB9xRqd0mA8kMpwPwp7nxODzJXOiakvk=
deploy:
  skip_cleanup: true
  provider: script
  script: "./travis-build.sh"
  on:
    all_branches: true
