FROM rabbitmq:3.5.3

# Add script to create default users / vhosts
ADD Dockerfile-rabbitmq-dev-init.sh /init.sh

# Set correct executable permissions
RUN chmod +x /init.sh

# Define default command
CMD ["/init.sh"]
