development:
  vhost: /nuntium/development
  user: nuntium.development
  pass: nuntium.development

test:
  vhost: /nuntium/development
  user: nuntium.development
  pass: nuntium.development

production:
  vhost: /nuntium
  user: nuntium
  pass: nuntium

travis:
  vhost: /
  user: guest
  pass: guest
