# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c2458375af37d2dac1e03e2e8e452b84f6f5b893a1bc0a693781ec8e359ce17b86212075a6a82cb83abbc2ba068f4776b930fbc01cc44dbae51d1e89c1c46f02

test:
  secret_key_base: 0a0d6213ea20342daf7dc2c426609d0063d6aac0b3b92d5566eaa5c37c7643651d751b1eead0385af445f5da40183c79398ec6d323a39ebfcfcfcb048247ce09

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
