
Country.create!(:name =>'Afghanistan', :iso2 => 'AF', :iso3 => 'AFG', :phone_prefix => '93', :clickatell_name => 'Afghanistan')
Country.create!(:name =>'Albania', :iso2 => 'AL', :iso3 => 'ALB', :phone_prefix => '355', :clickatell_name => 'Albania')
Country.create!(:name =>'Algeria', :iso2 => 'DZ', :iso3 => 'DZA', :phone_prefix => '213', :clickatell_name => 'Algeria')

Country.create!(:name =>'Andorra', :iso2 => 'AD', :iso3 => 'AND', :phone_prefix => '376', :clickatell_name => 'Andorra')
Country.create!(:name =>'Angola', :iso2 => 'AO', :iso3 => 'AGO', :phone_prefix => '244', :clickatell_name => 'Angola')
Country.create!(:name =>'Anguilla', :iso2 => 'AI', :iso3 => 'AIA', :phone_prefix => '1264', :clickatell_name => 'Anguilla')

Country.create!(:name =>'Antigua and Barbuda', :iso2 => 'AG', :iso3 => 'ATG', :phone_prefix => '1268', :clickatell_name => 'Antigua & Barbuda')
Country.create!(:name =>'Argentina', :iso2 => 'AR', :iso3 => 'ARG', :phone_prefix => '54', :clickatell_name => 'Argentina')
Country.create!(:name =>'Armenia', :iso2 => 'AM', :iso3 => 'ARM', :phone_prefix => '374', :clickatell_name => 'Armenia')
Country.create!(:name =>'Aruba', :iso2 => 'AW', :iso3 => 'ABW', :phone_prefix => '297', :clickatell_name => 'Aruba')
Country.create!(:name =>'Australia', :iso2 => 'AU', :iso3 => 'AUS', :phone_prefix => '61', :clickatell_name => 'Australia')
Country.create!(:name =>'Austria', :iso2 => 'AT', :iso3 => 'AUT', :phone_prefix => '43', :clickatell_name => 'Austria')
Country.create!(:name =>'Azerbaijan', :iso2 => 'AZ', :iso3 => 'AZE', :phone_prefix => '994', :clickatell_name => 'Azerbaijan')
Country.create!(:name =>'Bahamas', :iso2 => 'BS', :iso3 => 'BHS', :phone_prefix => '1242', :clickatell_name => 'Bahamas, the')
Country.create!(:name =>'Bahrain', :iso2 => 'BH', :iso3 => 'BHR', :phone_prefix => '973', :clickatell_name => 'Bahrain')
Country.create!(:name =>'Bangladesh', :iso2 => 'BD', :iso3 => 'BGD', :phone_prefix => '880', :clickatell_name => 'Bangladesh')
Country.create!(:name =>'Barbados', :iso2 => 'BB', :iso3 => 'BRB', :phone_prefix => '1246', :clickatell_name => 'Barbados')
Country.create!(:name =>'Belarus', :iso2 => 'BY', :iso3 => 'BLR', :phone_prefix => '375', :clickatell_name => 'Belarus')
Country.create!(:name =>'Belgium', :iso2 => 'BE', :iso3 => 'BEL', :phone_prefix => '32', :clickatell_name => 'Belgium')
Country.create!(:name =>'Belize', :iso2 => 'BZ', :iso3 => 'BLZ', :phone_prefix => '501', :clickatell_name => 'Belize')
Country.create!(:name =>'Benin', :iso2 => 'BJ', :iso3 => 'BEN', :phone_prefix => '229', :clickatell_name => 'Benin')
Country.create!(:name =>'Bermuda', :iso2 => 'BM', :iso3 => 'BMU', :phone_prefix => '1441', :clickatell_name => 'Bermuda')
Country.create!(:name =>'Bhutan', :iso2 => 'BT', :iso3 => 'BTN', :phone_prefix => '975', :clickatell_name => 'Bhutan')
Country.create!(:name =>'Bolivia', :iso2 => 'BO', :iso3 => 'BOL', :phone_prefix => '591', :clickatell_name => 'Bolivia')
Country.create!(:name =>'Bosnia and Herzegovina', :iso2 => 'BA', :iso3 => 'BIH', :phone_prefix => '387', :clickatell_name => 'Bosnia-Herzegovina')
Country.create!(:name =>'Botswana', :iso2 => 'BW', :iso3 => 'BWA', :phone_prefix => '267', :clickatell_name => 'Botswana')
Country.create!(:name =>'Brazil', :iso2 => 'BR', :iso3 => 'BRA', :phone_prefix => '55', :clickatell_name => 'Brazil')

Country.create!(:name =>'British Virgin Islands', :iso2 => 'VG', :iso3 => 'VGB', :phone_prefix => '1284', :clickatell_name => 'British Virgin Islands')
Country.create!(:name =>'Brunei', :iso2 => 'BN', :iso3 => 'BRN', :phone_prefix => '673', :clickatell_name => 'Brunei')
Country.create!(:name =>'Bulgaria', :iso2 => 'BG', :iso3 => 'BGR', :phone_prefix => '359', :clickatell_name => 'Bulgaria')
Country.create!(:name =>'Burkina Faso', :iso2 => 'BF', :iso3 => 'BFA', :phone_prefix => '226', :clickatell_name => 'Burkina Faso')
Country.create!(:name =>'Burma (Myanmar)', :iso2 => 'MM', :iso3 => 'MMR', :phone_prefix => '95', :clickatell_name => '')
Country.create!(:name =>'Burundi', :iso2 => 'BI', :iso3 => 'BDI', :phone_prefix => '257', :clickatell_name => 'Burundi')
Country.create!(:name =>'Cambodia', :iso2 => 'KH', :iso3 => 'KHM', :phone_prefix => '855', :clickatell_name => 'Cambodia')
Country.create!(:name =>'Cameroon', :iso2 => 'CM', :iso3 => 'CMR', :phone_prefix => '237', :clickatell_name => 'Cameroon')
Country.create!(:name =>'Canada', :iso2 => 'CA', :iso3 => 'CAN', :phone_prefix => '1', :clickatell_name => 'Canada')
Country.create!(:name =>'Cape Verde', :iso2 => 'CV', :iso3 => 'CPV', :phone_prefix => '238', :clickatell_name => 'Cape Verde')
Country.create!(:name =>'Cayman Islands', :iso2 => 'KY', :iso3 => 'CYM', :phone_prefix => '1345', :clickatell_name => 'Cayman Islands')
Country.create!(:name =>'Central African Republic', :iso2 => 'CF', :iso3 => 'CAF', :phone_prefix => '236', :clickatell_name => 'Central African Republic')
Country.create!(:name =>'Chad', :iso2 => 'TD', :iso3 => 'TCD', :phone_prefix => '235', :clickatell_name => 'Chad')
Country.create!(:name =>'Chile', :iso2 => 'CL', :iso3 => 'CHL', :phone_prefix => '56', :clickatell_name => 'Chile')
Country.create!(:name =>'China', :iso2 => 'CN', :iso3 => 'CHN', :phone_prefix => '86', :clickatell_name => 'China')
Country.create!(:name =>'Christmas Island', :iso2 => 'CX', :iso3 => 'CXR', :phone_prefix => '61', :clickatell_name => '')
Country.create!(:name =>'Cocos (Keeling) Islands', :iso2 => 'CC', :iso3 => 'CCK', :phone_prefix => '61', :clickatell_name => '')
Country.create!(:name =>'Colombia', :iso2 => 'CO', :iso3 => 'COL', :phone_prefix => '57', :clickatell_name => 'Colombia')
Country.create!(:name =>'Comoros', :iso2 => 'KM', :iso3 => 'COM', :phone_prefix => '269', :clickatell_name => 'Comoros')
Country.create!(:name =>'Cook Islands', :iso2 => 'CK', :iso3 => 'COK', :phone_prefix => '682', :clickatell_name => 'Cook Islands')
Country.create!(:name =>'Costa Rica', :iso2 => 'CR', :iso3 => 'CRC', :phone_prefix => '506', :clickatell_name => 'Costa Rica')
Country.create!(:name =>'Croatia', :iso2 => 'HR', :iso3 => 'HRV', :phone_prefix => '385', :clickatell_name => 'Croatia')
Country.create!(:name =>'Cuba', :iso2 => 'CU', :iso3 => 'CUB', :phone_prefix => '53', :clickatell_name => 'Cuba')
Country.create!(:name =>'Cyprus', :iso2 => 'CY', :iso3 => 'CYP', :phone_prefix => '357', :clickatell_name => 'Cyprus')
Country.create!(:name =>'Czech Republic', :iso2 => 'CZ', :iso3 => 'CZE', :phone_prefix => '420', :clickatell_name => 'Czech Republic')
Country.create!(:name =>'Democratic Republic of the Congo', :iso2 => 'CD', :iso3 => 'COD', :phone_prefix => '243', :clickatell_name => 'Congo, Democratic Republic')
Country.create!(:name =>'Denmark', :iso2 => 'DK', :iso3 => 'DNK', :phone_prefix => '45', :clickatell_name => 'Denmark')
Country.create!(:name =>'Djibouti', :iso2 => 'DJ', :iso3 => 'DJI', :phone_prefix => '253', :clickatell_name => '')
Country.create!(:name =>'Dominica', :iso2 => 'DM', :iso3 => 'DMA', :phone_prefix => '1767', :clickatell_name => 'Dominica')
Country.create!(:name =>'Dominican Republic', :iso2 => 'DO', :iso3 => 'DOM', :phone_prefix => '1809', :clickatell_name => 'Dominican Republic')

Country.create!(:name =>'Ecuador', :iso2 => 'EC', :iso3 => 'ECU', :phone_prefix => '593', :clickatell_name => 'Ecuador')
Country.create!(:name =>'Egypt', :iso2 => 'EG', :iso3 => 'EGY', :phone_prefix => '20', :clickatell_name => 'Egypt')
Country.create!(:name =>'El Salvador', :iso2 => 'SV', :iso3 => 'SLV', :phone_prefix => '503', :clickatell_name => 'El Salvador')
Country.create!(:name =>'Equatorial Guinea', :iso2 => 'GQ', :iso3 => 'GNQ', :phone_prefix => '240', :clickatell_name => '')
Country.create!(:name =>'Eritrea', :iso2 => 'ER', :iso3 => 'ERI', :phone_prefix => '291', :clickatell_name => '')
Country.create!(:name =>'Estonia', :iso2 => 'EE', :iso3 => 'EST', :phone_prefix => '372', :clickatell_name => 'Estonia')
Country.create!(:name =>'Ethiopia', :iso2 => 'ET', :iso3 => 'ETH', :phone_prefix => '251', :clickatell_name => 'Ethiopia')
Country.create!(:name =>'Falkland Islands', :iso2 => 'FK', :iso3 => 'FLK', :phone_prefix => '500', :clickatell_name => '')
Country.create!(:name =>'Faroe Islands', :iso2 => 'FO', :iso3 => 'FRO', :phone_prefix => '298', :clickatell_name => 'Faroe Islands')
Country.create!(:name =>'Fiji', :iso2 => 'FJ', :iso3 => 'FJI', :phone_prefix => '679', :clickatell_name => 'Fiji')
Country.create!(:name =>'Finland', :iso2 => 'FI', :iso3 => 'FIN', :phone_prefix => '358', :clickatell_name => 'Finland')
Country.create!(:name =>'France', :iso2 => 'FR', :iso3 => 'FRA', :phone_prefix => '33', :clickatell_name => 'France')

Country.create!(:name =>'French Polynesia', :iso2 => 'PF', :iso3 => 'PYF', :phone_prefix => '689', :clickatell_name => 'French Polynesia')

Country.create!(:name =>'Gabon', :iso2 => 'GA', :iso3 => 'GAB', :phone_prefix => '241', :clickatell_name => 'Gabon')
Country.create!(:name =>'Gambia', :iso2 => 'GM', :iso3 => 'GMB', :phone_prefix => '220', :clickatell_name => 'Gambia')

Country.create!(:name =>'Georgia', :iso2 => 'GE', :iso3 => 'GEO', :phone_prefix => '995', :clickatell_name => 'Georgia')
Country.create!(:name =>'Germany', :iso2 => 'DE', :iso3 => 'DEU', :phone_prefix => '49', :clickatell_name => 'Germany')
Country.create!(:name =>'Ghana', :iso2 => 'GH', :iso3 => 'GHA', :phone_prefix => '233', :clickatell_name => 'Ghana')
Country.create!(:name =>'Gibraltar', :iso2 => 'GI', :iso3 => 'GIB', :phone_prefix => '350', :clickatell_name => 'Gibraltar')
Country.create!(:name =>'Greece', :iso2 => 'GR', :iso3 => 'GRC', :phone_prefix => '30', :clickatell_name => 'Greece')
Country.create!(:name =>'Greenland', :iso2 => 'GL', :iso3 => 'GRL', :phone_prefix => '299', :clickatell_name => 'Greenland')
Country.create!(:name =>'Grenada', :iso2 => 'GD', :iso3 => 'GRD', :phone_prefix => '1473', :clickatell_name => 'Grenada')

Country.create!(:name =>'Guam', :iso2 => 'GU', :iso3 => 'GUM', :phone_prefix => '1671', :clickatell_name => 'Guam')
Country.create!(:name =>'Guatemala', :iso2 => 'GT', :iso3 => 'GTM', :phone_prefix => '502', :clickatell_name => 'Guatemala')

Country.create!(:name =>'Guinea', :iso2 => 'GN', :iso3 => 'GIN', :phone_prefix => '224', :clickatell_name => 'Guinea')
Country.create!(:name =>'Guinea-Bissau', :iso2 => 'GW', :iso3 => 'GNB', :phone_prefix => '245', :clickatell_name => '')
Country.create!(:name =>'Guyana', :iso2 => 'GY', :iso3 => 'GUY', :phone_prefix => '592', :clickatell_name => 'Guyana')
Country.create!(:name =>'Haiti', :iso2 => 'HT', :iso3 => 'HTI', :phone_prefix => '509', :clickatell_name => 'Haiti')
Country.create!(:name =>'Holy See (Vatican City)', :iso2 => 'VA', :iso3 => 'VAT', :phone_prefix => '39', :clickatell_name => '')
Country.create!(:name =>'Honduras', :iso2 => 'HN', :iso3 => 'HND', :phone_prefix => '504', :clickatell_name => 'Honduras')
Country.create!(:name =>'Hong Kong', :iso2 => 'HK', :iso3 => 'HKG', :phone_prefix => '852', :clickatell_name => 'HongKong')
Country.create!(:name =>'Hungary', :iso2 => 'HU', :iso3 => 'HUN', :phone_prefix => '36', :clickatell_name => 'Hungary')
Country.create!(:name =>'Iceland', :iso2 => 'IS', :iso3 => 'IS ', :phone_prefix => '354', :clickatell_name => 'Iceland')
Country.create!(:name =>'India', :iso2 => 'IN', :iso3 => 'IND', :phone_prefix => '91', :clickatell_name => 'India')
Country.create!(:name =>'Indonesia', :iso2 => 'ID', :iso3 => 'IDN', :phone_prefix => '62', :clickatell_name => 'Indonesia')
Country.create!(:name =>'Iran', :iso2 => 'IR', :iso3 => 'IRN', :phone_prefix => '98', :clickatell_name => 'Iran')
Country.create!(:name =>'Iraq', :iso2 => 'IQ', :iso3 => 'IRQ', :phone_prefix => '964', :clickatell_name => 'Iraq')
Country.create!(:name =>'Ireland', :iso2 => 'IE', :iso3 => 'IRL', :phone_prefix => '353', :clickatell_name => 'Ireland')
Country.create!(:name =>'Isle of Man', :iso2 => 'IM', :iso3 => 'IMN', :phone_prefix => '44', :clickatell_name => 'Isle of Man')
Country.create!(:name =>'Israel', :iso2 => 'IL', :iso3 => 'ISR', :phone_prefix => '972', :clickatell_name => 'Israel')
Country.create!(:name =>'Italy', :iso2 => 'IT', :iso3 => 'ITA', :phone_prefix => '39', :clickatell_name => 'Italy')
Country.create!(:name =>'Ivory Coast', :iso2 => 'CI', :iso3 => 'CIV', :phone_prefix => '225', :clickatell_name => 'Ivory Coast')
Country.create!(:name =>'Jamaica', :iso2 => 'JM', :iso3 => 'JAM', :phone_prefix => '1876', :clickatell_name => 'Jamaica')
Country.create!(:name =>'Japan', :iso2 => 'JP', :iso3 => 'JPN', :phone_prefix => '81', :clickatell_name => 'Japan')
Country.create!(:name =>'Jersey', :iso2 => 'JE', :iso3 => 'JEY', :phone_prefix => '44', :clickatell_name => 'Jersey')
Country.create!(:name =>'Jordan', :iso2 => 'JO', :iso3 => 'JOR', :phone_prefix => '962', :clickatell_name => 'Jordan')
Country.create!(:name =>'Kazakhstan', :iso2 => 'KZ', :iso3 => 'KAZ', :phone_prefix => '7', :clickatell_name => 'Kazakhstan')
Country.create!(:name =>'Kenya', :iso2 => 'KE', :iso3 => 'KEN', :phone_prefix => '254', :clickatell_name => 'Kenya')
Country.create!(:name =>'Kiribati', :iso2 => 'KI', :iso3 => 'KIR', :phone_prefix => '686', :clickatell_name => '')

Country.create!(:name =>'Kuwait', :iso2 => 'KW', :iso3 => 'KWT', :phone_prefix => '965', :clickatell_name => 'Kuwait')
Country.create!(:name =>'Kyrgyzstan', :iso2 => 'KG', :iso3 => 'KGZ', :phone_prefix => '996', :clickatell_name => 'Kyrgyzstan')
Country.create!(:name =>'Laos', :iso2 => 'LA', :iso3 => 'LAO', :phone_prefix => '856', :clickatell_name => 'Lao')
Country.create!(:name =>'Latvia', :iso2 => 'LV', :iso3 => 'LVA', :phone_prefix => '371', :clickatell_name => 'Latvia')
Country.create!(:name =>'Lebanon', :iso2 => 'LB', :iso3 => 'LBN', :phone_prefix => '961', :clickatell_name => 'Lebanon')
Country.create!(:name =>'Lesotho', :iso2 => 'LS', :iso3 => 'LSO', :phone_prefix => '266', :clickatell_name => '')
Country.create!(:name =>'Liberia', :iso2 => 'LR', :iso3 => 'LBR', :phone_prefix => '231', :clickatell_name => 'Liberia')
Country.create!(:name =>'Libya', :iso2 => 'LY', :iso3 => 'LBY', :phone_prefix => '218', :clickatell_name => 'Libya')
Country.create!(:name =>'Liechtenstein', :iso2 => 'LI', :iso3 => 'LIE', :phone_prefix => '423', :clickatell_name => 'Liechtenstein')
Country.create!(:name =>'Lithuania', :iso2 => 'LT', :iso3 => 'LTU', :phone_prefix => '370', :clickatell_name => 'Lithuania')
Country.create!(:name =>'Luxembourg', :iso2 => 'LU', :iso3 => 'LUX', :phone_prefix => '352', :clickatell_name => 'Luxembourg')
Country.create!(:name =>'Macau', :iso2 => 'MO', :iso3 => 'MAC', :phone_prefix => '853', :clickatell_name => 'Macau')
Country.create!(:name =>'Macedonia', :iso2 => 'MK', :iso3 => 'MKD', :phone_prefix => '389', :clickatell_name => 'Macedonia')
Country.create!(:name =>'Madagascar', :iso2 => 'MG', :iso3 => 'MDG', :phone_prefix => '261', :clickatell_name => 'Madagascar')
Country.create!(:name =>'Malawi', :iso2 => 'MW', :iso3 => 'MWI', :phone_prefix => '265', :clickatell_name => 'Malawi')
Country.create!(:name =>'Malaysia', :iso2 => 'MY', :iso3 => 'MYS', :phone_prefix => '60', :clickatell_name => 'Malaysia')
Country.create!(:name =>'Maldives', :iso2 => 'MV', :iso3 => 'MDV', :phone_prefix => '960', :clickatell_name => 'Maldives')
Country.create!(:name =>'Mali', :iso2 => 'ML', :iso3 => 'MLI', :phone_prefix => '223', :clickatell_name => 'Mali')
Country.create!(:name =>'Malta', :iso2 => 'MT', :iso3 => 'MLT', :phone_prefix => '356', :clickatell_name => 'Malta')

Country.create!(:name =>'Marshall Islands', :iso2 => 'MH', :iso3 => 'MHL', :phone_prefix => '692', :clickatell_name => '')
Country.create!(:name =>'Mauritania', :iso2 => 'MR', :iso3 => 'MRT', :phone_prefix => '222', :clickatell_name => 'Mauritania')
Country.create!(:name =>'Mauritius', :iso2 => 'MU', :iso3 => 'MUS', :phone_prefix => '230', :clickatell_name => 'Mauritius')
Country.create!(:name =>'Mayotte', :iso2 => 'YT', :iso3 => 'MYT', :phone_prefix => '262', :clickatell_name => '')
Country.create!(:name =>'Mexico', :iso2 => 'MX', :iso3 => 'MEX', :phone_prefix => '52', :clickatell_name => 'Mexico')
Country.create!(:name =>'Micronesia', :iso2 => 'FM', :iso3 => 'FSM', :phone_prefix => '691', :clickatell_name => '')
Country.create!(:name =>'Moldova', :iso2 => 'MD', :iso3 => 'MDA', :phone_prefix => '373', :clickatell_name => 'Moldova')
Country.create!(:name =>'Monaco', :iso2 => 'MC', :iso3 => 'MCO', :phone_prefix => '377', :clickatell_name => 'Monaco (Kosovo)')
Country.create!(:name =>'Mongolia', :iso2 => 'MN', :iso3 => 'MNG', :phone_prefix => '976', :clickatell_name => 'Mongolia')
Country.create!(:name =>'Montenegro', :iso2 => 'ME', :iso3 => 'MNE', :phone_prefix => '382', :clickatell_name => 'Montenegro')
Country.create!(:name =>'Montserrat', :iso2 => 'MS', :iso3 => 'MSR', :phone_prefix => '1664', :clickatell_name => 'Montserrat')
Country.create!(:name =>'Morocco', :iso2 => 'MA', :iso3 => 'MAR', :phone_prefix => '212', :clickatell_name => 'Morocco')
Country.create!(:name =>'Mozambique', :iso2 => 'MZ', :iso3 => 'MOZ', :phone_prefix => '258', :clickatell_name => 'Mozambique')
Country.create!(:name =>'Namibia', :iso2 => 'NA', :iso3 => 'NAM', :phone_prefix => '264', :clickatell_name => 'Namibia')

Country.create!(:name =>'Nepal', :iso2 => 'NP', :iso3 => 'NPL', :phone_prefix => '977', :clickatell_name => 'Nepal')
Country.create!(:name =>'Netherlands', :iso2 => 'NL', :iso3 => 'NLD', :phone_prefix => '31', :clickatell_name => 'Netherlands')
Country.create!(:name =>'Netherlands Antilles', :iso2 => 'AN', :iso3 => 'ANT', :phone_prefix => '599', :clickatell_name => 'Netherlands Antilles')
Country.create!(:name =>'New Caledonia', :iso2 => 'NC', :iso3 => 'NCL', :phone_prefix => '687', :clickatell_name => 'New Caledonia')
Country.create!(:name =>'New Zealand', :iso2 => 'NZ', :iso3 => 'NZL', :phone_prefix => '64', :clickatell_name => 'New Zealand')
Country.create!(:name =>'Nicaragua', :iso2 => 'NI', :iso3 => 'NIC', :phone_prefix => '505', :clickatell_name => 'Nicaragua')
Country.create!(:name =>'Niger', :iso2 => 'NE', :iso3 => 'NER', :phone_prefix => '227', :clickatell_name => 'Niger')
Country.create!(:name =>'Nigeria', :iso2 => 'NG', :iso3 => 'NGA', :phone_prefix => '234', :clickatell_name => 'Nigeria')
Country.create!(:name =>'Niue', :iso2 => 'NU', :iso3 => 'NIU', :phone_prefix => '683', :clickatell_name => '')
Country.create!(:name =>'Norfolk Island', :iso2 => '', :iso3 => 'NFK', :phone_prefix => '672', :clickatell_name => '')
Country.create!(:name =>'North Korea', :iso2 => 'KP', :iso3 => 'PRK', :phone_prefix => '850', :clickatell_name => '')
Country.create!(:name =>'Northern Mariana Islands', :iso2 => 'MP', :iso3 => 'MNP', :phone_prefix => '1670', :clickatell_name => '')
Country.create!(:name =>'Norway', :iso2 => 'NO', :iso3 => 'NOR', :phone_prefix => '47', :clickatell_name => 'Norway')
Country.create!(:name =>'Oman', :iso2 => 'OM', :iso3 => 'OMN', :phone_prefix => '968', :clickatell_name => 'Oman')
Country.create!(:name =>'Pakistan', :iso2 => 'PK', :iso3 => 'PAK', :phone_prefix => '92', :clickatell_name => 'Pakistan')
Country.create!(:name =>'Palau', :iso2 => 'PW', :iso3 => 'PLW', :phone_prefix => '680', :clickatell_name => '')


Country.create!(:name =>'Panama', :iso2 => 'PA', :iso3 => 'PAN', :phone_prefix => '507', :clickatell_name => 'Panama')
Country.create!(:name =>'Papua New Guinea', :iso2 => 'PG', :iso3 => 'PNG', :phone_prefix => '675', :clickatell_name => 'Papua New Guinea')
Country.create!(:name =>'Paraguay', :iso2 => 'PY', :iso3 => 'PRY', :phone_prefix => '595', :clickatell_name => 'Paraguay')
Country.create!(:name =>'Peru', :iso2 => 'PE', :iso3 => 'PER', :phone_prefix => '51', :clickatell_name => 'Peru')
Country.create!(:name =>'Philippines', :iso2 => 'PH', :iso3 => 'PHL', :phone_prefix => '63', :clickatell_name => 'Philippines')
Country.create!(:name =>'Pitcairn Islands', :iso2 => 'PN', :iso3 => 'PCN', :phone_prefix => '870', :clickatell_name => '')
Country.create!(:name =>'Poland', :iso2 => 'PL', :iso3 => 'POL', :phone_prefix => '48', :clickatell_name => 'Poland')
Country.create!(:name =>'Portugal', :iso2 => 'PT', :iso3 => 'PRT', :phone_prefix => '351', :clickatell_name => 'Portugal')
Country.create!(:name =>'Puerto Rico', :iso2 => 'PR', :iso3 => 'PRI', :phone_prefix => '1', :clickatell_name => 'Puerto Rico')
Country.create!(:name =>'Qatar', :iso2 => 'QA', :iso3 => 'QAT', :phone_prefix => '974', :clickatell_name => 'Qatar')
Country.create!(:name =>'Republic of the Congo', :iso2 => 'CG', :iso3 => 'COG', :phone_prefix => '242', :clickatell_name => 'Congo')

Country.create!(:name =>'Romania', :iso2 => 'RO', :iso3 => 'ROU', :phone_prefix => '40', :clickatell_name => 'Romania')
Country.create!(:name =>'Russia', :iso2 => 'RU', :iso3 => 'RUS', :phone_prefix => '7', :clickatell_name => 'Russia')
Country.create!(:name =>'Rwanda', :iso2 => 'RW', :iso3 => 'RWA', :phone_prefix => '250', :clickatell_name => 'Rwanda')
Country.create!(:name =>'Saint Barthelemy', :iso2 => 'BL', :iso3 => 'BLM', :phone_prefix => '590', :clickatell_name => '')
Country.create!(:name =>'Saint Helena', :iso2 => 'SH', :iso3 => 'SHN', :phone_prefix => '290', :clickatell_name => '')
Country.create!(:name =>'Saint Kitts and Nevis', :iso2 => 'KN', :iso3 => 'KNA', :phone_prefix => '1869', :clickatell_name => 'St. Kitts And Nevis')
Country.create!(:name =>'Saint Lucia', :iso2 => 'LC', :iso3 => 'LCA', :phone_prefix => '1758', :clickatell_name => 'St. Lucia')
Country.create!(:name =>'Saint Martin', :iso2 => 'MF', :iso3 => 'MAF', :phone_prefix => '1599', :clickatell_name => '')
Country.create!(:name =>'Saint Pierre and Miquelon', :iso2 => 'PM', :iso3 => 'SPM', :phone_prefix => '508', :clickatell_name => '')
Country.create!(:name =>'Saint Vincent and the Grenadines', :iso2 => 'VC', :iso3 => 'VCT', :phone_prefix => '1784', :clickatell_name => 'St. Vincent')
Country.create!(:name =>'Samoa', :iso2 => 'WS', :iso3 => 'WSM', :phone_prefix => '685', :clickatell_name => '')
Country.create!(:name =>'San Marino', :iso2 => 'SM', :iso3 => 'SMR', :phone_prefix => '378', :clickatell_name => 'San Marino')
Country.create!(:name =>'Sao Tome and Principe', :iso2 => 'ST', :iso3 => 'STP', :phone_prefix => '239', :clickatell_name => '')
Country.create!(:name =>'Saudi Arabia', :iso2 => 'SA', :iso3 => 'SAU', :phone_prefix => '966', :clickatell_name => 'Saudi Arabia')
Country.create!(:name =>'Senegal', :iso2 => 'SN', :iso3 => 'SEN', :phone_prefix => '221', :clickatell_name => 'Senegal')
Country.create!(:name =>'Serbia', :iso2 => 'RS', :iso3 => 'SRB', :phone_prefix => '381', :clickatell_name => 'Serbia')
Country.create!(:name =>'Seychelles', :iso2 => 'SC', :iso3 => 'SYC', :phone_prefix => '248', :clickatell_name => 'Seychelles')
Country.create!(:name =>'Sierra Leone', :iso2 => 'SL', :iso3 => 'SLE', :phone_prefix => '232', :clickatell_name => 'Sierra Leone')
Country.create!(:name =>'Singapore', :iso2 => 'SG', :iso3 => 'SGP', :phone_prefix => '65', :clickatell_name => 'Singapore')
Country.create!(:name =>'Slovakia', :iso2 => 'SK', :iso3 => 'SVK', :phone_prefix => '421', :clickatell_name => 'Slovakia')
Country.create!(:name =>'Slovenia', :iso2 => 'SI', :iso3 => 'SVN', :phone_prefix => '386', :clickatell_name => 'Slovenia')
Country.create!(:name =>'Solomon Islands', :iso2 => 'SB', :iso3 => 'SLB', :phone_prefix => '677', :clickatell_name => '')
Country.create!(:name =>'Somalia', :iso2 => 'SO', :iso3 => 'SOM', :phone_prefix => '252', :clickatell_name => '')
Country.create!(:name =>'South Africa', :iso2 => 'ZA', :iso3 => 'ZAF', :phone_prefix => '27', :clickatell_name => 'South Africa')
Country.create!(:name =>'South Korea', :iso2 => 'KR', :iso3 => 'KOR', :phone_prefix => '82', :clickatell_name => 'Korea (South)')
Country.create!(:name =>'Spain', :iso2 => 'ES', :iso3 => 'ESP', :phone_prefix => '34', :clickatell_name => 'Spain')
Country.create!(:name =>'Sri Lanka', :iso2 => 'LK', :iso3 => 'LKA', :phone_prefix => '94', :clickatell_name => 'Sri Lanka')
Country.create!(:name =>'Sudan', :iso2 => 'SD', :iso3 => 'SDN', :phone_prefix => '249', :clickatell_name => 'Sudan')
Country.create!(:name =>'Suriname', :iso2 => 'SR', :iso3 => 'SUR', :phone_prefix => '597', :clickatell_name => 'Suriname')

Country.create!(:name =>'Swaziland', :iso2 => 'SZ', :iso3 => 'SWZ', :phone_prefix => '268', :clickatell_name => 'Swaziland')
Country.create!(:name =>'Sweden', :iso2 => 'SE', :iso3 => 'SWE', :phone_prefix => '46', :clickatell_name => 'Sweden')
Country.create!(:name =>'Switzerland', :iso2 => 'CH', :iso3 => 'CHE', :phone_prefix => '41', :clickatell_name => 'Switzerland')
Country.create!(:name =>'Syria', :iso2 => 'SY', :iso3 => 'SYR', :phone_prefix => '963', :clickatell_name => 'Syria')
Country.create!(:name =>'Taiwan', :iso2 => 'TW', :iso3 => 'TWN', :phone_prefix => '886', :clickatell_name => 'Taiwan')
Country.create!(:name =>'Tajikistan', :iso2 => 'TJ', :iso3 => 'TJK', :phone_prefix => '992', :clickatell_name => 'Tajikistan')
Country.create!(:name =>'Tanzania', :iso2 => 'TZ', :iso3 => 'TZA', :phone_prefix => '255', :clickatell_name => 'Tanzania')
Country.create!(:name =>'Thailand', :iso2 => 'TH', :iso3 => 'THA', :phone_prefix => '66', :clickatell_name => 'Thailand')
Country.create!(:name =>'Timor-Leste', :iso2 => 'TL', :iso3 => 'TLS', :phone_prefix => '670', :clickatell_name => '')
Country.create!(:name =>'Togo', :iso2 => 'TG', :iso3 => 'TGO', :phone_prefix => '228', :clickatell_name => 'Togo')
Country.create!(:name =>'Tokelau', :iso2 => 'TK', :iso3 => 'TKL', :phone_prefix => '690', :clickatell_name => '')
Country.create!(:name =>'Tonga', :iso2 => 'TO', :iso3 => 'TON', :phone_prefix => '676', :clickatell_name => 'Tonga Islands')
Country.create!(:name =>'Trinidad and Tobago', :iso2 => 'TT', :iso3 => 'TTO', :phone_prefix => '1868', :clickatell_name => 'Trinidad and Tobago')
Country.create!(:name =>'Tunisia', :iso2 => 'TN', :iso3 => 'TUN', :phone_prefix => '216', :clickatell_name => 'Tunisia')
Country.create!(:name =>'Turkey', :iso2 => 'TR', :iso3 => 'TUR', :phone_prefix => '90', :clickatell_name => 'Turkey')
Country.create!(:name =>'Turkmenistan', :iso2 => 'TM', :iso3 => 'TKM', :phone_prefix => '993', :clickatell_name => 'Turkmenistan')
Country.create!(:name =>'Turks and Caicos Islands', :iso2 => 'TC', :iso3 => 'TCA', :phone_prefix => '1649', :clickatell_name => 'Turks and Caicos Islands')
Country.create!(:name =>'Tuvalu', :iso2 => 'TV', :iso3 => 'TUV', :phone_prefix => '688', :clickatell_name => '')
Country.create!(:name =>'US Virgin Islands', :iso2 => 'VI', :iso3 => 'VIR', :phone_prefix => '1340', :clickatell_name => 'US Virgin Islands')
Country.create!(:name =>'Uganda', :iso2 => 'UG', :iso3 => 'UGA', :phone_prefix => '256', :clickatell_name => 'Uganda')
Country.create!(:name =>'Ukraine', :iso2 => 'UA', :iso3 => 'UKR', :phone_prefix => '380', :clickatell_name => 'Ukraine')
Country.create!(:name =>'United Arab Emirates', :iso2 => 'AE', :iso3 => 'ARE', :phone_prefix => '971', :clickatell_name => 'United Arab Emirates')
Country.create!(:name =>'United Kingdom', :iso2 => 'GB', :iso3 => 'GBR', :phone_prefix => '44', :clickatell_name => 'UK')
Country.create!(:name =>'United States', :iso2 => 'US', :iso3 => 'USA', :phone_prefix => '1', :clickatell_name => '')
Country.create!(:name =>'Uruguay', :iso2 => 'UY', :iso3 => 'URY', :phone_prefix => '598', :clickatell_name => 'Uruguay')
Country.create!(:name =>'Uzbekistan', :iso2 => 'UZ', :iso3 => 'UZB', :phone_prefix => '998', :clickatell_name => 'Uzbekistan')
Country.create!(:name =>'Vanuatu', :iso2 => 'VU', :iso3 => 'VUT', :phone_prefix => '678', :clickatell_name => 'Vanuatu')
Country.create!(:name =>'Venezuela', :iso2 => 'VE', :iso3 => 'VEN', :phone_prefix => '58', :clickatell_name => 'Venezuela')
Country.create!(:name =>'Vietnam', :iso2 => 'VN', :iso3 => 'VNM', :phone_prefix => '84', :clickatell_name => 'Vietnam')
Country.create!(:name =>'Wallis and Futuna', :iso2 => 'WF', :iso3 => 'WLF', :phone_prefix => '681', :clickatell_name => '')


Country.create!(:name =>'Yemen', :iso2 => 'YE', :iso3 => 'YEM', :phone_prefix => '967', :clickatell_name => 'Yemen')
Country.create!(:name =>'Zambia', :iso2 => 'ZM', :iso3 => 'ZMB', :phone_prefix => '260', :clickatell_name => 'Zambia')
Country.create!(:name =>'Zimbabwe', :iso2 => 'ZW', :iso3 => 'ZWE', :phone_prefix => '263', :clickatell_name => 'Zimbabwe')
